### ISSUE TITLE
Can not load MongoDBLibrary successfully

### ISSUE THREAD

**Issue by lijing8428** [iPlantCollaborativeOpenSource/Robotframework-MongoDB-Library#12]
Import this library in RIDE: MongoDBLibrary, it raises an error.
error in RIDE log: 
Importing test library 'MongoDBLibrary' failed: ImportError: No module named objectid
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 143, in _import
    return __import__(name, fromlist=fromlist)
  File "C:\Python27\lib\site-packages\MongoDBLibrary__init__.py", line 2, in <module>
    from mongoquery import MongoQuery
  File "C:\Python27\lib\site-packages\MongoDBLibrary\mongoquery.py", line 2, in <module>
    from bson.objectid import ObjectId

how to resolve it?

**Comment by jerry57** [comment]
Do you have mongo.py installed?  MongoDBLibrary will not load if mongo.py is not installed.

**Comment by lijing8428** [comment]
I  uninstall  pymongo 3.3.0 and reinstall pymongo 3.0.3 and resolve the problem. 
The latest version of pymongo is 3.3.0, I guess MongoDBLibrary 0.3.2 is not compatible with it.
